// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Pid.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_PID_H_
#define _FAST_DDS_GENERATED_PID_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Pid_SOURCE)
#define Pid_DllAPI __declspec( dllexport )
#else
#define Pid_DllAPI __declspec( dllimport )
#endif // Pid_SOURCE
#else
#define Pid_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Pid_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure Pid defined by the user in the IDL file.
 * @ingroup PID
 */
class Pid
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Pid();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Pid();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Pid that will be copied.
     */
    eProsima_user_DllExport Pid(
            const Pid& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Pid that will be copied.
     */
    eProsima_user_DllExport Pid(
            Pid&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Pid that will be copied.
     */
    eProsima_user_DllExport Pid& operator =(
            const Pid& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Pid that will be copied.
     */
    eProsima_user_DllExport Pid& operator =(
            Pid&& x);

    /*!
     * @brief Comparison operator.
     * @param x Pid object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Pid& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Pid object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Pid& x) const;

    /*!
     * @brief This function sets a value in member v_1
     * @param _v_1 New value for member v_1
     */
    eProsima_user_DllExport void v_1(
            float _v_1);

    /*!
     * @brief This function returns the value of member v_1
     * @return Value of member v_1
     */
    eProsima_user_DllExport float v_1() const;

    /*!
     * @brief This function returns a reference to member v_1
     * @return Reference to member v_1
     */
    eProsima_user_DllExport float& v_1();

    /*!
     * @brief This function sets a value in member v_2
     * @param _v_2 New value for member v_2
     */
    eProsima_user_DllExport void v_2(
            float _v_2);

    /*!
     * @brief This function returns the value of member v_2
     * @return Value of member v_2
     */
    eProsima_user_DllExport float v_2() const;

    /*!
     * @brief This function returns a reference to member v_2
     * @return Reference to member v_2
     */
    eProsima_user_DllExport float& v_2();

    /*!
     * @brief This function sets a value in member v_3
     * @param _v_3 New value for member v_3
     */
    eProsima_user_DllExport void v_3(
            float _v_3);

    /*!
     * @brief This function returns the value of member v_3
     * @return Value of member v_3
     */
    eProsima_user_DllExport float v_3() const;

    /*!
     * @brief This function returns a reference to member v_3
     * @return Reference to member v_3
     */
    eProsima_user_DllExport float& v_3();

    /*!
     * @brief This function sets a value in member v_4
     * @param _v_4 New value for member v_4
     */
    eProsima_user_DllExport void v_4(
            float _v_4);

    /*!
     * @brief This function returns the value of member v_4
     * @return Value of member v_4
     */
    eProsima_user_DllExport float v_4() const;

    /*!
     * @brief This function returns a reference to member v_4
     * @return Reference to member v_4
     */
    eProsima_user_DllExport float& v_4();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const Pid& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    float m_v_1;
    float m_v_2;
    float m_v_3;
    float m_v_4;
};

#endif // _FAST_DDS_GENERATED_PID_H_